general {
    lock_cmd = pidof hyprlock || hyprlock --immediate-render --no-fade-in
    unlock_cmd = niri msg action power-on-monitors
    before_sleep_cmd = loginctl lock-session; sleep 0.5; niri msg action power-off-monitors; sleep 1
    after_sleep_cmd = niri msg action power-on-monitors
    ignore_dbus_inhibit = false
}

listener {
    timeout = 60
    on-timeout = loginctl lock-session
}

listener {
    timeout = 90
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}
