general {
    lock_cmd = pidof hyprlock || ~/.config/waybar/scripts/lock-screen.sh
    before_sleep_cmd = ~/.config/waybar/scripts/prepare-sleep.sh
    after_sleep_cmd = niri msg action power-on-monitors
    ignore_dbus_inhibit = false
}

listener {
    timeout = 60
    on-timeout = ~/.config/waybar/scripts/lock-screen.sh
}

listener {
    timeout = 90
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}
