wireplumber.settings = {
  node.stream.restore-target = false
}

monitor.alsa.rules = [
  {
    matches = [ { node.name = "~alsa_input.*" }, { node.name = "~alsa_output.*" } ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 5
        node.pause-on-idle = true
      }
    }
  }
  {
    matches = [ { node.name = "~alsa_output.*skl_hda_dsp_generic.*" } ]
    actions = {
      update-props = {
        # Avoid the SOF HDMI mmap resume failure.
        api.alsa.disable-mmap = true
      }
    }
  }
]
